parent: $LVSR/exp/wsj/configs/wsj_jan_baseline.yaml
net:
    dims_bidir: [250, 250, 250, 250]
    subsample: [1, 1, 2, 2]
    bottom:
      dims: []
    # 0.5 times respective settings from wsj_jan_baseline.yaml
    prior:
        before: 100
        after: 100
        initial_begin: 0
        initial_end: 40
        min_speed: 1.2
        max_speed: 2.2
regularization:
    max_norm: 1.0

