parent: $LVSR/exp/wsj/configs/wsj_good.yaml
data:
    dataset: wsj.h5

    name_mapping:
        train: train_si284
        valid: test_dev93
        test:  test_eval92

    normalization: ""
    recordings_source: fbank_dd
    labels_source: characters
    add_eos: True
    preprocess_text: False
    preprocess_features: ""
net:
    # 0.8 times respective settings from wsj_good_fbank.yaml
    prior:
        initial_begin: 0
        initial_end: 160
        min_speed: 4.8
        max_speed: 8.8
        before: 400
        after: 400


