map:
    parent:
        type: str
    cmd_args:
        type: any
    data:
        map:
            batch_size:
                type: int
            max_length:
                type: int
            normalization:
                type: str
            sort_k_batches:
                type: str
            dataset:
                type: str
            recordings_source:
                type: str
            labels_source:
                type: str
            preprocess_features:
                type: str
            preprocess_text:
                type: bool
            add_eos:
                type: bool
            add_bos:
                type: int
            # legacy, not supported any more
            prepend_eos:
                type: bool
    net:
        map:
            dim_dec:
                type: int
            dims_bidir:
                sequence:
                    - type: int
            dims_bottom:
                sequence:
                    - type: int
            post_merge_dims:
                sequence:
                    - type: int
            conv_n:
                type: int
            bottom_activation:
                type: any
            post_merge_activation:
                type: any
            enc_transition:
                type: any
            dec_transition:
                type: any
            subsample:
                sequence:
                    - type: int
            attention_type:
                type: str
            use_states_for_readout:
                type: bool
            criterion:
                map:
                    name:
                        type: str
                    min_reward:
                        type: int
            lm:
                type: any
            prior:
                map:
                    before:
                        type: int
                    after:
                        type: int
                    initial_begin:
                        type: int
                    initial_end:
                        type: int
                    min_speed:
                        type: float
                    max_speed:
                        type: float
                    type:
                        type: str
    regularization:
        map:
            dropout:
                type: bool
            noise:
                type: float
            max_norm:
                type: float
    initialization:
        matching-rule: any
        map:
            regex;(/.*):
                matching-rule: any
                map:
                    regex;(weights_init|biases_init|rec_weights_init|initial_states_init):
                        type: any
    training:
        map:
            num_batches:
                type: int
            num_epochs:
                type: int
            gradient_threshold:
                type: float
            scale:
                type: float
            momentum:
                type: float
            epsilon:
                type: float
            decay_rate:
                type: float
            rules:
                sequence:
                    - type: str
            exploration:
                type: bool
            restart_from:
                type: str
    stages:
        type: any
    vocabulary:
        type: str
