parent: $LVSR/lvsr/configs/wsj_paper1.yaml
net:
    dims_bidir: [250, 250, 250, 250]
    subsample: [1, 1, 1, 1]
    prior:
        before: 400
        after: 400
        type: window_around_median
stages:
    pretraining:
        net:
            prior:
                type: expanding
                initial_begin: 0
                initial_end: 160
                min_speed: 4.8
                max_speed: 8.8
