parent: $LVSR/lvsr/configs/wsj_prior_conv.yaml
training:
    rules: 
        - momentum
        - adadelta
    scale: 0.1
    decay_rate: 0.95
    epsilon: 1.0e-8
net:
    use_states_for_readout: True
    bottom_activation: !!python/object/apply:blocks.bricks.Rectifier []
data:
    preprocess_text: True
    preprocess_features: log_spectrogram
