parent: $LVSR/lvsr/configs/wsj_paper1.yaml
net:
    dims_bidir: [250, 250, 250, 250]
    subsample: [1, 2, 2, 2]
    prior:
        before: 50
        after: 50
        type: window_around_median
stages:
    pretraining:
        net:
            prior:
                type: expanding
                initial_begin: 0
                initial_end: 20
                min_speed: 0.6
                max_speed: 1.1
